<?php
/**
 * @file
 * Create entities when install the module and delete them when uninstall.
 */

/**
 * Implements hook_install().
 */
function xvt_drupal8_test_install() {
  // Create editor.
  $user_info = array(
    'field_title' => 'Mr',
    'name' => 'editor',
    'mail' => 'editor@xvt.com',
    'roles' => array('editor'),
    'pass' => 'abc123',
    'status' => 1,
  );
  $account = entity_create('user', $user_info);
  $account->save();

  // Create terms.
  $terms_array = array(
    'Tutorial' => 'very-important',
    'Article' => 'not-important',
    'Guide' => 'important',
  );
  // Loop all the terms to create.
  foreach($terms_array as $section => $priority) {
    $term_value = array(
      'vid' => 'section',
      'name' => $section,
      'field_priority' => $priority,
    );
    $term = entity_create('taxonomy_term', $term_value);
    $term->save();
  }
}

/**
 * Implements hook_uninstall().
 */
function xvt_drupal8_test_uninstall() {
  // Delete user - editor.
  $user = user_load_by_name('editor');
  if (is_object($user)) {
    $user->delete();
  }

  // Delete terms in section vocabulary.
  $terms_array = array(
    'Tutorial',
    'Article',
    'Guide',
  );
  // Loop all the term's name.
  foreach($terms_array as $term_name) {
    // Loop all the term entity.
    foreach(taxonomy_term_load_multiple_by_name($term_name, 'section') as $term) {
      $term->delete();
    }
  }
}
