<?php
/**
 * @file
 * Functions and hooks to implement special handling for xvt page.
 */

/**
 * Implements hook_node_insert().
 */
function xvt_drupal8_test_node_insert($node) {
  // Check the content type if page then show the message after creation.
  if (strtolower($node->type->entity->label()) === 'page') {
    drupal_set_message(t('You just created a new Page.'), 'status');
  }
}

/**
 * Implements hook_preprocess_html().
 */
function xvt_drupal8_test_preprocess_html(&$var) {
  // Get the current uri.
  $current_uri = \Drupal::request()->getRequestUri();
  // Check if login page before showing the messages.
  if ($current_uri === '/user/login') {
    drupal_set_message(t('This website is using cookies.'), 'status');
  }
}

